### ISSUE TITLE
Kafka 0.9 Consumer API

### ISSUE THREAD

**Issue by williamsjj** [ciena/afkak#1]
Are there any plans to adopt the Kafka 0.9 consumer API that allows rebalancing?

**Comment by rthille** [comment]
Yeah, I'm working on 0.9 compatibility right now.  First is just getting it to work with current functionality, but I'll definitely be adding the rebalancing consumer functionality in the (hopefully near) future.

**Comment by twm** [comment]
An update: I plan to merge the out-of-tree coordinated consumer implementation we've been using here this month.
