### ISSUE TITLE
PyPi package missing

### ISSUE THREAD

**Issue by renstrom** [ciena/afkak#10]
The readme says "Afkak releases are available on PyPI."[1], but there are no packages for afkak on pypi.python.org and the like is a 404.

[1] https://github.com/ciena/afkak#install

**Comment by rthille** [comment]
Sorry about that. Fixed.

**Comment by duynguyen-ew** [comment]
@rthille can you push tag 2.4.0 too? pypi's version is 2.4.0 but I could not find that tag in the repo.

**Comment by rthille** [comment]
Done
