### ISSUE TITLE
When is the lz4 compression format supported?

### ISSUE THREAD

**Issue by houxiyao** [ciena/afkak#100]

**Comment by twm** [comment]
Afkak doesn't currently support LZ4 compression, but it should be straightforward to add. Here's an outline of what it would take.

First, mark the codec supported:

https://github.com/ciena/afkak/blob/b7e0a716881ff776e15843465586a4cbd942cb6c/afkak/common.py#L37-L39

Add an extra for the required dependency here:

https://github.com/ciena/afkak/blob/b7e0a716881ff776e15843465586a4cbd942cb6c/setup.py#L29-L32

Add encoding support here:

https://github.com/ciena/afkak/blob/b7e0a716881ff776e15843465586a4cbd942cb6c/afkak/kafkacodec.py#L929-L936

Add decoding support here:

https://github.com/ciena/afkak/blob/b7e0a716881ff776e15843465586a4cbd942cb6c/afkak/kafkacodec.py#L266-L282

And most importantly, add unit and integration tests that exercise this code path.
