### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by rthille** [ciena/afkak#117]
bash-3.2$ git clone https://github.com/ciena/afkak.git
Cloning into 'afkak'...
remote: Enumerating objects: 78, done.        
remote: Counting objects: 100% (78/78), done.        
remote: Compressing objects: 100% (54/54), done.        
remote: Total 4855 (delta 39), reused 51 (delta 23), pack-reused 4777        
Receiving objects: 100% (4855/4855), 1.41 MiB | 1004.00 KiB/s, done.
Resolving
Resolving deltas: 100% (3655/3655), done.
bash-3.2$ cd afkak/
bash-3.2$ make toxi
Makefile:28: *** Version in setup.py (20.10.0) does not match afkak/__init__.py (20.9.0).  Stop.
bash-3.2$

**Comment by twm** [comment]
Ah... can you tell I don't use the Makefile? :confused:
