### ISSUE TITLE
Error starting a new consumer group when earliest offset > 0

### ISSUE THREAD

**Issue by stephenhenderson** [ciena/afkak#13]
Hi,

I think I've found a bug when trying to start a new consumer-group consumer against a partition (i.e. there is no committed offset for the group in kafka) and the earliest offset in the partition is > 0, e.g. because the kafka log cleaner has deleted old messages.

e.g. consumer created and started like:
```
consumer = Consumer(
    client=my_kafka_client,
    topic="mytopic",
    partition=0,
    processor=my_event_handler,
    consumer_group="myroup",
)
consumer.start(OFFSET_COMMITTED)
```
If the earliest offset in the partition is > 0 the consumer will loop indefinitely giving this error:
```
Failure fetching messages from kafka: <twisted.python.failure.Failure afkak.common.OffsetOutOfRangeError: FetchResponse(topic='mytopic', partition=0, error=1, highwaterMark=-1, messages=<generator object _decode_message_set_iter at 0x0000000107623d80>)>
```

I believe this is what's happening in the background:
* Kafka topic has one partition, earliest offset is 10.
* New consumer sends initial OffsetFetchRequest for partition and consumer_group=foo.
* Kafka has no committed offset for foo, returns OffsetFetchResponse with `offset = -1`.
* Afkak sets consumer._fetch_offset to `-1 + 1 = 0`
* Consumer makes fetch request for offset=0
* Kafka returns OffsetOutOfRangeError since 0 < 10.
* Afkak loops infinitely re-requesting messages from offset=0

Suggested Fix:
* Check for -1 in the offset response and set the offset to OFFSET_EARLIEST, e.g.
```
def _handle_offset_response(self, response):
    ...
   response = response[0]
   if hasattr(response, 'offsets'):
       # It's a response to an OffsetRequest
       self._fetch_offset = response.offsets[0]
   else:
       # It's a response to an OffsetFetchRequest
       if response.offset == -1:
           # Kafka has no committed offset for this group 
           # so read from earliest available
           self._fetch_offset = OFFSET_EARLIEST
       else: 
           self._fetch_offset = response.offset + 1

        self._last_committed_offset = response.offset
        ...
```

I've tried this locally and it seems to work but I'm struggling to write a suitable unit test for this case to submit a patch.

Regards,
Stephen

**Comment by rthille** [comment]
Stephen,
Thanks so much for the input. I'll try to fix this and write the test this weekend.
