### ISSUE TITLE
Status of afkak wrt Kafka 1.0?

### ISSUE THREAD

**Issue by raarts** [ciena/afkak#15]
Hi,

I am evaluating message systems, and Kafka is a big contender. Unfortunately many of our client systems still run CentOS6,  python3 is out of the question, and everything uses twisted. Since this library seems to be the most applicable one for my use case, I am wondering about the maintenance status. I've seen issues that mention some features of 0.9 not being implemented yet, and the last commit has also been a long time ago. More recent forks do not seem to exist.

What are the plans with this library? Thanks.

**Comment by rthille** [comment]
We've got changes in-house @Ciena to implement the Coordinated Consumer, but we've been going through release-push after release-push, so I haven't had time to get them cleaned up and pushed up to public github.com.  We're planning on moving to Kafka 1.0 for our brokers in the near term (few months), so it should at least be compatible, if not have the added features (past coordinated consumers) once that happens.

**Comment by twm** [comment]
We are also partway through a Python 3 port.

**Comment by raarts** [comment]
Thanks for answering. Currently not interested in Python 3 (old code base), but very interested in the Coordinated Consumer.

**Comment by twm** [comment]
I should probably say that the reason most development is happening internally is because we haven't had time to set up CI on this repo, which is #12. We don't really want to keep this stuff hidden, it's just we're not willing to go without automated testing. :)

**Comment by dougiewright** [comment]
Hey folks. Sorry to bump an older issue - but wondering about the status of afkak with kafka versions above 0.9. We're testing it against 1.1.0 brokers and having some issues, and assume from this discussion that we shouldn't actually expect it to work?

**Comment by rthille** [comment]
@dougiewright: I'm no longer @ciena (at a startup and have no free time) but I know they are moving to a newer Kafka broker and so @twm will probably be tasked with making Afkak work with that newer version.  In the mean time, I'd file issues here with any failures you are seeing.

**Comment by twm** [comment]
@dougiewright I've taken a look through the Kafka changelog and while it looks like using the older protocol messages Afkak currently supports is not optimal (the broker may translate them to newer formats), it seems like everything should still work. We also have some internal users on 1.1._x_ with no apparent issues. Could you elaborate on the issues you are seeing?

**Comment by dougiewright** [comment]
@twm - so what it looks like for us is very similar to https://github.com/ciena/afkak/issues/18

on 1.1.x, our producers work for a while, and then will stop producing messages and the log fills with "Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x00000000177d7d00>" messages.

We're not running within a docker container though.

**Comment by rthille** [comment]
@dougiewright Not sure you can handle the extreme flood of debug level logging from afkak for as long as it takes to get to that error, but if you can get the debug-level stream that might help us debug what's going on...

**Comment by twm** [comment]
@dougiewright Do you by any change rely on `domain` or `search` directives in `/etc/resolv.conf`? Afkak uses Twisted's `twisted.names.client` to do the DNS lookups (that's what generates those log messages), but that resolver [doesn't support `domain` or `search`](http://twistedmatrix.com/trac/ticket/6090).

I mention this because Docker containers commonly have weird `/etc/resolv.conf` files, so it would explain why the symptoms resemble those in #18. It doesn't explain the delayed nature of your problems, though. Does Afkak produce any warnings or errors which might help point us in the right direction?

**Comment by dougiewright** [comment]
Hey @rthille and @twm - thanks for the pointers. So we DO have a search directive in the resolv.conf (specfically `search ec2.internal`)

What is strange is that we can use afkak just fine against 0.8.2, but as soon as we upgrade the kafka cluster to 1.1.0, we start to see this behaviour.

We're trying to wrap a synchronous kafka-python client and use it within twisted to get around it, but this is coming with its own issues!

I will try and grab some debug level logging at some point over the next couple of days.
