### ISSUE TITLE
Running on CentOS 6 w/twisted 8.2.0

### ISSUE THREAD

**Issue by raarts** [ciena/afkak#16]
Hi, I need to run on CentOS6.  Would that be a big problem for me when implementing afkak?

**Comment by twm** [comment]
I'm not sure. Does CentOS 6 ship Python 2.6 or 2.7? Afkak is not tested against Python 2.6. Twisted has already dropped support for Python 2.6.

We also don't test against such an old Twisted. Using such an old Twisted frankly isn't a good idea in any case. You may need to patch Afkak to work with it, and I don't think we'd want to take those patches here.

**Comment by raarts** [comment]
It's python 2.6.6. But thanks. I'll need to try it out. Can't upgrade twisted or python unfortunately, due to third party software.
