### ISSUE TITLE
pip install does not work

### ISSUE THREAD

**Issue by rolele** [ciena/afkak#5]
```
root@spider:/code# pip install afkak
Collecting afkak
  Could not find a version that satisfies the requirement afkak (from versions: )
No matching distribution found for afkak
```

also is this plugin compatible with python3?

**Comment by rthille** [comment]
Definitely not python3 tested.

**Comment by Julian** [comment]
@rolele it's just not on PyPI (which yeah I too would love to request), but installing it straight out of github with pip works just fine.

**Comment by rthille** [comment]
Uploaded to PyPi. Should be fixed.
