### ISSUE TITLE
Publish afkak releases to PyPI

### ISSUE THREAD

**Issue by wiml** [ciena/afkak#67]
It would be convenient to be able to install Afkak using "pip install afkak". It looks like only 2.4.0 was ever published to pypi, although `pip install 'git+https://github.com/ciena/afkak.git@2.9.0#egg=afkak'` does work in the meantime.

Putting new releases on pypi also aids in discoverability of the project.

**Comment by twm** [comment]
Yikes, 2.4 is atrociously old. I will fix this after the holidays. It is time to put together a proper release procedure.

In the meantime, you might use `pip install 'https://github.com/ciena/afkak/archive/2.9.0.tar.gz'`. Then you don't need Git on the target system.

**Comment by twm** [comment]
I have published 2.9.0 and the 3.0.0 development snapshots to PyPI.

**Comment by twm** [comment]
I was leaving this open because I haven't written up a release procedure yet, but I'm going to go ahead and close this in favor of #79.
