### ISSUE TITLE
CPU Spikes

### ISSUE THREAD

**Issue by Julian** [ciena/afkak#7]
Hey there.

I'm in the middle of diagnosing this for us, so if I find the culprit I'll just close with the right resolution, but by any chance, have you guys noticed that CPU spikes and memory tanks if the Kafka cluster goes unreliable, even if it comes back again?

I.e., that the library actually doesn't recover for producers when kafka does?

Cheers,
-J

**Comment by rthille** [comment]
No.  We've seen issues with the library not re-resolving hostnames properly in all cases though.  Did you lose connections to all your brokers and have them all change IPs?

**Comment by Julian** [comment]
Lose connections yes, but they all come back with the same (elastic) IPs.

My guess now is that there might be a missing `addErrback` somewhere, and that the CPU spikes are the app struggling to keep up with generating tracebacks (and killing the JIT looking at stack frames) but I still don't have a good guess yet as to what's up, and certainly it looks like we don't heal and start to produce again to Kafka even long after the cluster comes back up.

Will follow up as soon as I pin this down.

**Comment by Julian** [comment]
I still want to follow up here, but yeah I'm almost certain at this point that it's not `afkak`'s direct fault, it might be us trying to send `afkak` errors to sentry or something. Will try to follow up with more specifics but closing for now to not clutter your issues with non-issues :)
